### ISSUE TITLE
优化团队首页的内容

### ISSUE THREAD

**Issue by samzong** [cskefu/.github#1]
## 概述

我们可以通过对团队首页进行优化，暂时想到如下内容：

* 提供 新开发者 对春松客服的的多个 repo 之间的阅读路径
* 对我们的团队的介绍
* 春松客服想要打造的一个产品是什么，传递价值观

## 代码版本

* 根据 Github 的设定，可以以 README.md 的形式来实现，实现路径为团队空间下 [profile/README.md](profile/README.md)

**Comment by hailiang-wang** [comment]
没问题，这周内找时间弄。

**Comment by hailiang-wang** [comment]
Docs about `Customizing your organization's profile`

https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile

**Comment by hailiang-wang** [comment]
For Member view's profile, 

Create a private repository called .github-private. Once created, add a /profile/README.md. The README will appear on your organization's profile, visible only to members of the organization.

[Read documentation](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile)
